### PR TITLE
(MODULES-9191) support a non-root user

### PR DESCRIPTION
**Pull request by tkishel**
Support running agents without root privileges.

### CODE REVIEW

**Comment by tkishel** [comment]
Travis fails with Ruby: 2.1.9 (the Ruby we ship with Puppet 4 / PE 2016.4) here:

spec/fixtures/modules/scheduled_task/lib/puppet/provider/scheduled_task/taskscheduler_api2.rb

But the code of the `device_manager` module itself does not call `match?` at al. 
So `device_manager` is actually compatible with Ruby: 2.1.9 / Puppet 4 / PE 2016.4. 

We could remove support for Puppet 4 / PE 2016.4, or ... ?

**Comment by Thomas-Franklin** [comment]
> Travis fails with Ruby: 2.1.9 (the Ruby we ship with Puppet 4 / PE 2016.4) here:
> 
> spec/fixtures/modules/scheduled_task/lib/puppet/provider/scheduled_task/taskscheduler_api2.rb
> 
> But the code of the `device_manager` module itself does not call `match?` at al.
> So `device_manager` is actually compatible with Ruby: 2.1.9 / Puppet 4 / PE 2016.4.
> 
> We could remove support for Puppet 4 / PE 2016.4, or ... ?

The changes have happened in the scheduled_task module, and we have it pinned to master which is why we've caught it in this PR as the change has only happened in the last ~9 days. My guess they are prepping for removal of support of Puppet 4 / Ruby 2.1.

Removing support of Puppet 4 would correlate with other modules where support for Puppet 4 has already been removed.

**Comment by tkishel** [comment]
If I cannot go back in time and submit the PR two weeks ago :) I'm okay with dropping support for Puppet 4 in the next release, but I defer to your team; and maintenance like this is not a process I'm familiar with, would it simply involve updating the following?

appveyor.yml
metadata.json
.gitlab-ci.yml
.rubocop.yml
.travis.yml

**Comment by tkishel** [comment]
Or, if someone on the team can do the maintenance, I'll submit after that :)

**Comment by Thomas-Franklin** [comment]
> Or, if someone on the team can do the maintenance, I'll submit after that :)

I'll aim to get the maintenance done in next hour or two, and then you can rebase if that's okay?

**Comment by tkishel** [comment]
That might best. I am consistently in your debt!

**Comment by tkishel** [comment]
I'm working out of the Singapore office this week, so will not be able to revisit this until (my) tomorrow morning, so do not feel any need to rush.

**Comment by Thomas-Franklin** [comment]
The removal of Puppet 4 should be in master, a rebase should fix the failures.

**Comment by tkishel** [comment]
Do I need to rename the branch from WIP?

**Comment by Thomas-Franklin** [comment]
Branch is fine, just the commit :-)

**Comment by tkishel** [comment]
`identity` is a fact:

```
[root@pe-201910-agent ~]# facter identity.user
root

[root@pe-201910-agent ~]# sudo -u davids facter identity.user
davids
```

**Comment by DavidS** [comment]
augh - I now see it in the ticket description. This is actually not what I was thinking about at all :-/

I'd like folks to be able to deploy `puppet device` configurations from a root-running agent into a unprivileged user.

**Comment by tkishel** [comment]
!!!

Could you provide a longer description, with an example?

I'm happy to work on that, and think this is still a valid enhancement as is.

**Comment by DavidS** [comment]
Merging this as it is for now. Will amend the ticket with a better description.

**Pull request merged**
