### PR TITLE
(WIP) Specify default values when using Hiera or the Classifier

### PR DESCRIPTION
**Pull request by tkishel**
This commit implements global and device-type levels of default values.

### CODE REVIEW

**Comment by DavidS** [comment]
The failure on travis is likely due to https://github.com/bundler/bundler/issues/6629, and we're working on a fix for that.

**Comment by tkishel** [comment]
I tested the functions indirectly via `spec/classes/devices_spec.rb` but see that I should have added tests to `spec/functions/*.rb` :(

**Comment by tkishel** [comment]
Added commit that updates documentation and examples

**Comment by shermdog** [comment]
This is amazing.  I'm all about this!

**Comment by shermdog** [comment]
Will merge once the commits are squashed and renamed :)

**Comment by tkishel** [comment]
Is there an existing/do we need a Jira ticket for (the name of) this?

**Comment by tkishel** [comment]
Created FM-7230, renamed the branch, and squashed the commits in #24

**Pull request closed without merging**
