### PR TITLE
(FM 7115) return device certificates with task results

### PR DESCRIPTION
**Pull request by tkishel**
(FM-7115) return device certificates with task results

Include each target's certificate fingerprint in task results.

### CODE REVIEW

**Comment by tphoney** [comment]
Nice fixup, this would benefit greatly from some acceptance tests, to prevent regressions later on. There are example of task testing here https://github.com/puppetlabs/puppetlabs-service/blob/master/spec/acceptance/init_spec.rb or in apache or mysql

**Comment by tkishel** [comment]
Added acceptance tests.
TODO: moving those tests out of configure_spec.rb and comparing the fingerprint.

**Comment by tphoney** [comment]
@tkishel i am looking at separating out the device stuff you implemented into its own test. Bit busy today, so apologies for not having it ready sooner.

**Comment by tphoney** [comment]
a commit soon 🤞

**Comment by tphoney** [comment]
https://github.com/tkishel/device_manager/pull/1

**Comment by tkishel** [comment]
No worries! I was working on this in parallel. Let me know if the latest commit is 'too big'.

**Comment by tphoney** [comment]
small rubocop fix. also can you rename the acceptance task test, to indicate it is a task test

**Comment by tkishel** [comment]
Done! Thanks!

**Pull request merged**
